### PR TITLE
Add portuguese translation

### PR DESCRIPTION
**Pull request by matheusfelipeog**
I did the file manager translation 👍

### CODE REVIEW

**Comment by andersevenrud** [comment]
Awesome! Much appreciated :)

**Comment by andersevenrud** [comment]
Referencing to https://github.com/os-js/osjs-panels/pull/34#issuecomment-585463197

there's also new translations coming up here as well :)

https://github.com/os-js/osjs-filemanager-application/pull/14/files#diff-720e1df800dfb9096d48e894cc6e90b0

**Comment by andersevenrud** [comment]
Correction: https://github.com/os-js/osjs-filemanager-application/blob/chore/refactor-2020/locales.js

**Comment by matheusfelipeog** [comment]
Right, I will opening a new pr for panels and filemanager ;)

**Pull request merged**
